apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-responder-ingress
  annotations:
    haproxy.org/ssl-redirect: "true"
spec:
  ingressClassName: haproxy
  tls:
    - secretName: ingress-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: first-responder-service
                port:
                  number: 8080
