apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: first-responder

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - vllm-pvc.yaml
  - vllm-service.yaml
  - vllm-deployment.yaml
