apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Override the container image tag/registry for the local environment
images:
  - name: first-responder
    newName: k3s-registry.apps.k3s-dom.local/first-responder
    newTag: latest

# Generate the TLS secret from certs created by generate-certs.sh
secretGenerator:
  - name: ingress-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=certs/tls.crt
      - tls.key=certs/tls.key
    options:
      disableNameSuffixHash: true
  - name: llm-credentials
    envs:
      - secret.env
    options:
      disableNameSuffixHash: true

generatorOptions:
  labels:
    app.kubernetes.io/managed-by: kustomize
